version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    container_name: minio_storage
    image: minio/minio
    command: server /data
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioaccess
      MINIO_SECRET_KEY: miniosecret
    ports:
      - "9002:9000"
    volumes:
      - minio_data:/data

  backend:
    container_name: wagtail_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    container_name: nextjs_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  pg_data:
  minio_data:
